### ISSUE TITLE
how the "Overall" score in the table is calculated

### ISSUE THREAD

**Issue by mumuyeye** [MatthewCYM/VoiceBench#2]
I hope this message finds you well. I am currently studying your paper, and I find your work truly inspiring. However, I have a question regarding Table 3. Could you kindly clarify how the "Overall" score in the table is calculated? Specifically, I would like to understand whether it is an average of the listed scores, a weighted calculation, or derived using another method.

**Comment by MatthewCYM** [comment]
Hi,

Thank you for your interest in our work!

Currently, to compute the overall score, we first calculate a score (ranging from 0 to 100) for each individual task. The overall score is then obtained by averaging the scores across all tasks, as defined by the following formula:
```
overall=(20*alpaca+20*common+(sdqa_panda+sdqa_gpt)/2+openbook+(ifeval_instruct+ifeval_prompt)/2+advbench)/6
```
Please note that we recently identified some errors in the overall score computation in the arXiv version. For the most accurate and up-to-date overall scores, we recommend referring to the GitHub leaderboard.

**Comment by mumuyeye** [comment]
I am reaching out to seek clarification regarding the ranking data provided in the README of your repository. Could you kindly specify which part of the evaluation results in the paper these rankings correspond to? For instance, for Moshi's related data, does it refer to "text" or "audio"? Additionally, for tasks like SD-QA and IFEval, could you clarify which specific evaluation results these rankings are based on?

**Comment by MatthewCYM** [comment]
Hi, the leaderboard shows results with audio inputs. For SD-QA, the score shown represents the average accuracy calculated by Panda and GPT. For IFEval, it reflects the average of prompt-level and instruct-level accuracy.

**Comment by mumuyeye** [comment]
Thanks！

**Comment by MatthewCYM** [comment]
Hi,

A revised version of ArXiv with the corrected overall score is now available.
