### ISSUE TITLE
Feature Request: Add Ultravox model

### ISSUE THREAD

**Issue by kadirnar** [MatthewCYM/VoiceBench#4]
Ultravox: https://github.com/fixie-ai/ultravox
Demo: https://demo.ultravox.ai/

**Comment by MatthewCYM** [comment]
Hi,

Inference for the Ultravox model is now supported.

**Comment by kadirnar** [comment]
> Hi,
> 
> Inference for the Ultravox model is now supported.

Thank you for the quick development ❤️ Will you add it to the leaderboard table?

**Comment by MatthewCYM** [comment]
Hi,

The Ultravox model will be included in the leaderboard. We kindly encourage you to submit any new voice assistant results directly via the issue tracker. We will review the submissions and update the leaderboard accordingly.

Thank you!

**Comment by kadirnar** [comment]
Thanks for adding it to your leaderboard ❤️ I will test the 70B model. And I will share the results 🫡

**Comment by Gpwner** [comment]
@MatthewCYM are calling the ultravox api or test on local ?

**Comment by MatthewCYM** [comment]
I tested it on local.
