### ISSUE TITLE
Results of KE-Omni-v1.5

### ISSUE THREAD

**Issue by shuaijiang** [MatthewCYM/VoiceBench#5]
Here are the results of KE-Omni-v1.5, which has been fine-tuned from KE-Omni-v1.0 to enhance its safety capabilities.

| Model    | AlpacaEval | CommonEval | SD-QA |  MMSU | OpenBookQA | IFEval | AdvBench | Overall |
|-------------------------------|:----------:|:----------:|:-----:|:-----:|:----------:|:------:|:--------:|:-------:|
| KE-Omni-v1.5      |  3.82  |   3.20 | 31.20 | 32.27 |    58.46 |  15.00 |   100.00 |  53.90 |

**Comment by MatthewCYM** [comment]
Hi,

Thank you for sharing the results! We have updated the leaderboard accordingly.
